"""Metadata for the Threadsaw Phish Hunt factor catalog.

The catalog is intentionally data-only.  The GUI, CLI documentation, saved
configurations, and scoring engine all read the same definitions so the user
sees the same label, explanation, examples, prerequisites, and computational
load everywhere.

A factor being cataloged does not imply that its evaluator is available in the
current release.  ``implemented`` is explicit and the scoring engine returns
UNKNOWN for pending evaluators rather than pretending that the answer is NO.
"""
from __future__ import annotations

from typing import Any

LOAD_LEVELS = ("Light", "Moderate", "Heavy", "Extreme")
TOP_CATEGORY_LABELS = {
    "inherently_risky": "Inherently Risky",
    "situational": "Situational",
}


def _p(name: str, label: str, kind: str = "text", **kwargs: Any) -> dict[str, Any]:
    return {"name": name, "label": label, "kind": kind, **kwargs}


def _f(
    factor_id: str,
    label: str,
    top_category: str,
    subcategory: str,
    load: str,
    description: str,
    *,
    suspicious: list[str] | None = None,
    legitimate: list[str] | None = None,
    false_positive: str = "",
    prerequisites: list[str] | None = None,
    parameters: list[dict[str, Any]] | None = None,
    implemented: bool = False,
    evaluator_version: str = "catalog-1",
) -> dict[str, Any]:
    if load not in LOAD_LEVELS:
        raise ValueError(load)
    return {
        "factor_id": factor_id,
        "label": label,
        "top_category": top_category,
        "subcategory": subcategory,
        "load": load,
        "description": description,
        "suspicious_examples": suspicious or [],
        "legitimate_examples": legitimate or [],
        "false_positive_notes": false_positive,
        "prerequisites": prerequisites or [],
        "parameters": parameters or [],
        "implemented": implemented,
        "evaluator_version": evaluator_version,
    }


FACTOR_CATALOG: list[dict[str, Any]] = [
    # Inherently Risky — sender/header deception
    _f(
        "reply_to_domain_mismatch",
        "Reply-To domain differs from From domain",
        "inherently_risky",
        "Sender and Header Deception",
        "Light",
        "Checks whether the registrable domain in Reply-To differs from the visible From domain.",
        suspicious=['From: accounts@legitcompany.com; Reply-To: paymentdesk@external.test'],
        legitimate=['From: alerts@company.com; Reply-To: support@company.com'],
        false_positive="Mailing platforms, ticketing systems, and outsourced support services can legitimately use another Reply-To domain.",
    ),
    _f(
        "display_name_embedded_email_domain_mismatch",
        "Display name contains an email address with a different domain",
        "inherently_risky",
        "Sender and Header Deception",
        "Light",
        "Extracts email-like text from the sender display name and compares its domain with the actual sender address domain.",
        suspicious=['From: "janesmith@legitcompany.com" <janesmith@external.test>'],
        legitimate=['From: "Jane Smith" <janesmith@legitcompany.com>'],
    ),
    _f(
        "sender_domain_lookalike_configured",
        "Sender domain resembles a configured legitimate organization domain",
        "inherently_risky",
        "Sender and Header Deception",
        "Moderate",
        "Compares the sender domain with analyst-supplied legitimate domains using conservative local lookalike checks.",
        suspicious=['legitcornpany.com resembles configured legitcompany.com'],
        legitimate=['Exact match legitcompany.com is not flagged.'],
        false_positive="Similar names can belong to unrelated legitimate organizations. Configure only domains relevant to the investigation.",
        parameters=[_p("legitimate_domains", "Legitimate organization domains", "multiline")],
    ),
    _f(
        "sender_domain_lookalike_recipient",
        "Sender domain resembles a recipient domain but does not match",
        "inherently_risky",
        "Sender and Header Deception",
        "Moderate",
        "Compares the sender domain with recipient domains and flags a conservative lookalike mismatch.",
        suspicious=['From billing@legitcornpany.com to employee@legitcompany.com'],
        legitimate=['Exact sender/recipient domain matches are not flagged.'],
        prerequisites=["recipient data"],
    ),
    # Inherently Risky — security
    _f("trusted_dmarc_fail", "Trusted DMARC check failed", "inherently_risky", "Security Check Failures", "Light",
       "Uses only a stored Authentication-Results record marked trusted by conservative PST-corpus inference and explicitly reporting DMARC fail.",
       suspicious=["dmarc=fail from a PST-inferred trusted authentication service"],
       legitimate=["Missing, none, or untrusted results return UNKNOWN rather than YES."],
       prerequisites=["trusted authentication-result classification"]),
    _f("trusted_dkim_fail", "Trusted DKIM check failed", "inherently_risky", "Security Check Failures", "Light",
       "Uses only a stored Authentication-Results record marked trusted by conservative PST-corpus inference and explicitly reporting DKIM fail.",
       suspicious=["dkim=fail from a PST-inferred trusted authentication service"],
       legitimate=["No DKIM signature is UNKNOWN, not a failure."], prerequisites=["trusted authentication-result classification"]),
    _f("trusted_spf_fail", "Trusted SPF check failed", "inherently_risky", "Security Check Failures", "Light",
       "Uses stored SPF results marked trusted by conservative PST-corpus inference. FAIL, SOFTFAIL, and PERMERROR can match; TEMPERROR and missing results are UNKNOWN.",
       suspicious=["spf=fail client-ip=203.0.113.5"],
       legitimate=["spf=pass does not trigger; missing SPF is UNKNOWN."], prerequisites=["trusted authentication-result classification"]),
    # Inherently Risky — URL deception
    _f(
        "displayed_url_domain_mismatch",
        "Displayed URL domain differs from actual domain",
        "inherently_risky",
        "URL Deception and Obfuscation",
        "Moderate",
        "Checks links whose visible text itself looks like a URL/domain and compares it with the actual destination stored by Threadsaw.",
        suspicious=['Visible text: https://login.company.com; actual href: https://attacker.test/login'],
        legitimate=['A security gateway may rewrite the actual href while leaving the original URL visible.'],
        false_positive="This can produce false positives when the organization rewrites URLs. Disable this factor in URL-rewriting environments.",
        prerequisites=["URL indexing"],
    ),
    _f("url_literal_ip", "URL uses a literal IP address", "inherently_risky", "URL Deception and Obfuscation", "Moderate",
       "Checks whether a stored URL directly uses an IPv4 or IPv6 address instead of a hostname.",
       suspicious=["http://192.0.2.25/login", "https://[2001:db8::25]/document"],
       legitimate=["Some internal appliances use IP-address URLs."], prerequisites=["URL indexing"]),
    _f("url_userinfo_misdirection", "URL contains misleading user-information before the hostname", "inherently_risky", "URL Deception and Obfuscation", "Moderate",
       "Checks URL userinfo before @, which can make the left side look like the destination while the true host follows @.",
       suspicious=["https://login.legitcompany.com@malicious.test/account"], prerequisites=["URL indexing"]),
    _f("url_nonstandard_port", "URL uses a non-standard network port", "inherently_risky", "URL Deception and Obfuscation", "Moderate",
       "Checks explicit web ports other than HTTP 80 or HTTPS 443 without connecting to the host.",
       suspicious=["https://example.test:8443/login"], legitimate=["Some legitimate internal or development applications use non-standard ports."], prerequisites=["URL indexing"]),
    _f("url_dangerous_scheme", "URL uses a potentially dangerous URI scheme", "inherently_risky", "URL Deception and Obfuscation", "Moderate",
       "Checks a bundled conservative list of schemes that may invoke scripts, local resources, applications, or unusual protocol handlers.",
       suspicious=["file://", "smb://", "javascript:", "data:", "ms-msdt:", "search-ms:"],
       legitimate=["mailto: and tel: are not included by default."], prerequisites=["URL indexing"]),
    _f("url_embeds_legitimate_domain", "URL hostname embeds a configured legitimate domain outside the true registrable domain", "inherently_risky", "URL Deception and Obfuscation", "Moderate",
       "Checks for an analyst-supplied legitimate domain placed misleadingly in subdomain labels while another registrable domain controls the host.",
       suspicious=["microsoft.com.login.attacker.test (actual registrable domain attacker.test)"],
       legitimate=["login.microsoft.com is a genuine subdomain and is not flagged."],
       parameters=[_p("legitimate_domains", "Legitimate domains", "multiline")], prerequisites=["URL indexing"]),
    _f("url_obfuscated_numeric_ip", "URL uses an obfuscated numeric IP-address representation", "inherently_risky", "URL Deception and Obfuscation", "Moderate",
       "Recognizes local-only numeric IPv4 forms such as integer, hexadecimal, octal, or mixed-radix host text.",
       suspicious=["http://2130706433/", "http://0x7f000001/"], prerequisites=["URL indexing"]),
    # Inherently Risky — attachments
    _f("attachment_executable_or_script", "Attachment contains executable or script content", "inherently_risky", "Attachment Deception and Executable Content", "Light",
       "Reads the executable/script classification already stored during ingestion or attachment reporting. It never rescans the file during Phish Hunt.",
       suspicious=["PE executable, PowerShell, JavaScript, VBScript, batch, or shell script classification"],
       legitimate=["UNKNOWN means the earlier check was not run or was inconclusive."], prerequisites=["stored executable/script classification"]),
    _f("attachment_double_extension", "Attachment filename uses a double extension", "inherently_risky", "Attachment Deception and Executable Content", "Light",
       "Checks filenames that may disguise the final extension while excluding common compound formats such as tar.gz.",
       suspicious=["invoice.pdf.exe", "payment.docx.lnk"], legitimate=["archive.tar.gz is not flagged by itself."], prerequisites=["attachment metadata"]),
    _f("attachment_unicode_controls", "Attachment filename contains Unicode direction-control or invisible characters", "inherently_risky", "Attachment Deception and Executable Content", "Light",
       "Inspects stored filename code points for bidirectional overrides, zero-width characters, and related invisible formatting controls.",
       suspicious=["A filename visually appearing as invoice.pdf while hidden characters reorder its true suffix."],
       legitimate=["International text may legitimately contain some formatting controls, though they are unusual in filenames."], prerequisites=["attachment metadata"]),
    _f("executable_without_extension", "Executable or script attachment has no filename extension", "inherently_risky", "Attachment Deception and Executable Content", "Light",
       "Combines the existing executable/script classification with the stored filename and does not rescan bytes.",
       suspicious=["Filename Invoice; stored class Windows PE executable"], prerequisites=["stored executable/script classification"]),
    _f("attachment_shortcut", "Attachment is a shortcut or Internet shortcut file", "inherently_risky", "Attachment Deception and Executable Content", "Light",
       "Checks stored extensions/types for shortcut and launcher formats without resolving or launching them.",
       suspicious=["Document.lnk", "Secure Portal.url", "Payment.website"], prerequisites=["attachment metadata"]),
    _f("attachment_disk_image", "Attachment is a disk-image or container format", "inherently_risky", "Attachment Deception and Executable Content", "Light",
       "Checks stored attachment metadata for ISO, IMG, VHD, VHDX, DMG, and similar mountable container formats.",
       suspicious=["payload.iso", "documents.vhdx"], prerequisites=["attachment metadata"]),
    _f("attachment_html_svg", "Attachment is an HTML or SVG document", "inherently_risky", "Attachment Deception and Executable Content", "Light",
       "Checks stored filename extensions and declared MIME types for HTML, SHTML, XHTML, or SVG attachments. It does not render the attachment.",
       suspicious=["invoice.html", "secure-document.svg"],
       legitimate=["Web-development and design workflows may legitimately exchange these files."], prerequisites=["attachment metadata"]),
    _f("attachment_modern_loader_or_macro", "Attachment uses a modern loader, launcher, or macro-enabled Office extension", "inherently_risky", "Attachment Deception and Executable Content", "Light",
       "Checks stored filename extensions for WSF, WSH, SCR, PIF, CPL, CHM, XLL, ONE, IQY, SLK, RDP, MSIX, and macro-enabled Office formats such as DOCM, XLSM, and PPTM.",
       suspicious=["payment.wsf", "invoice.xll", "document.docm"],
       legitimate=["Administrators and power users may exchange RDP, XLL, or macro-enabled Office files for legitimate work."], prerequisites=["attachment metadata"]),
    # Inherently Risky — active HTML
    _f("html_form", "HTML form is embedded in the message body", "inherently_risky", "Active HTML Content", "Moderate",
       "Statically parses the stored HTML body for form and input elements. It never renders or submits the form.",
       suspicious=["<form><input type=password><button type=submit>"], prerequisites=["stored HTML body"]),
    _f("html_auto_redirect", "HTML body contains an automatic redirect", "inherently_risky", "Active HTML Content", "Moderate",
       "Statically checks the stored HTML for automatic redirect mechanisms such as meta refresh. Destinations remain inert text.",
       suspicious=['<meta http-equiv="refresh" content="0;url=https://example.test/login">'], prerequisites=["stored HTML body"]),
    _f("html_embedded_active_object", "HTML body contains an embedded frame or active-object element", "inherently_risky", "Active HTML Content", "Moderate",
       "Checks for iframe, frame, object, embed, and applet elements without rendering or retrieving referenced content.",
       suspicious=["<iframe src=...>", "<object data=...>"], prerequisites=["stored HTML body"]),
    _f("html_script", "HTML body contains a script element", "inherently_risky", "Active HTML Content", "Moderate",
       "Checks stored HTML for script elements. No script is executed.",
       suspicious=["<script>...</script>"], prerequisites=["stored HTML body"]),
    _f("html_event_handlers", "HTML body contains JavaScript event-handler attributes", "inherently_risky", "Active HTML Content", "Moderate",
       "Checks stored HTML for inline on* event attributes such as onerror or onclick. No script is executed.",
       suspicious=["<img onerror=...>", "<a onclick=...>"],
       legitimate=["Some poorly constructed marketing templates include harmless event-handler attributes."], prerequisites=["stored HTML body"]),

    # Situational — sender/domain history
    _f("return_path_domain_mismatch", "Return-Path domain differs from From domain", "situational", "Sender, Domain, and Infrastructure History", "Light",
       "Compares the registrable Return-Path and From domains.",
       suspicious=["From billing@company.com; Return-Path bounce@unrelated.test"],
       legitimate=["Legitimate mailing platforms commonly use a separate bounce domain."]),
    _f("sender_address_new", "Sender address is newly observed in the case", "situational", "Sender, Domain, and Infrastructure History", "Heavy",
       "Searches all earlier dated messages in the case for the same normalized sender address.",
       suspicious=["First appearance of a purported vendor address during the campaign window."],
       legitimate=["Every legitimate correspondent is new once."]),
    _f("sender_domain_new", "Sender domain is newly observed in the case", "situational", "Sender, Domain, and Infrastructure History", "Heavy",
       "Searches all earlier dated messages for any sender using the same registrable domain.",
       suspicious=["A new lookalike vendor domain first appears during the hunt."],
       legitimate=["A new legitimate vendor also introduces a new domain."]),
    _f("sender_ip_new_for_sender", "Sender infrastructure IP is newly observed for that sender", "situational", "Sender, Domain, and Infrastructure History", "Heavy",
       "Compares the current trusted-boundary IP with earlier IPs for the same sender. No lookup or geolocation occurs.",
       suspicious=["Established sender suddenly arrives through an unseen trusted-boundary IP."],
       legitimate=["Cloud mail providers routinely rotate outbound IP addresses."], prerequisites=["trusted boundary IP classification"]),
    _f("reply_to_new_for_sender", "Reply-To address is newly observed for that sender", "situational", "Sender, Domain, and Infrastructure History", "Heavy",
       "Compares the current Reply-To address/domain with earlier messages from the same sender.",
       suspicious=["A known vendor suddenly directs replies to an external mailbox."],
       legitimate=["A sender may legitimately change help-desk or billing addresses."]),
    _f("return_path_new_for_sender", "Return-Path domain is newly observed for that sender", "situational", "Sender, Domain, and Infrastructure History", "Heavy",
       "Compares the current Return-Path domain with earlier messages from the same sender.",
       suspicious=["A known sender suddenly uses unfamiliar delivery infrastructure."],
       legitimate=["Legitimate senders switch email-service providers."]),
    _f("sender_free_email_provider", "Sender uses a common free-email provider", "situational", "Sender, Domain, and Infrastructure History", "Light",
       "Compares the sender domain with a bundled, versioned static list of common consumer email providers. No live lookup occurs.",
       suspicious=["A purported corporate executive writes from a consumer mailbox."],
       legitimate=["Individuals and small organizations legitimately use consumer providers."], prerequisites=["bundled provider list"]),
    _f("sender_domain_punycode", "Sender email domain contains Punycode", "situational", "Sender, Domain, and Infrastructure History", "Light",
       "Checks the sender domain for xn-- labels and decodes them locally for review.",
       suspicious=["billing@xn--legitcompny-..."], legitimate=["Internationalized domains legitimately use Punycode."]),
    _f("sender_header_mismatch", "Sender header address differs from visible From address", "situational", "Sender, Domain, and Infrastructure History", "Moderate",
       "Parses the stored raw Sender header and compares it with the visible From address.",
       suspicious=["From payments@company.com; Sender delivery@external.test"],
       legitimate=["Delegated sending and mailing platforms legitimately use Sender."], prerequisites=["stored raw headers"]),

    # Situational — thread/relationship
    _f("corroborated_thread_reply", "Corroborated reply to an existing thread", "situational", "Thread and Relationship History", "Heavy",
       "Requires a thread-reference match to an earlier case message, plausible normalized subject continuity, and participant overlap.",
       suspicious=["Can be weighted upward when a campaign is known to hijack real threads."],
       legitimate=["A well-corroborated earlier thread can be weighted downward, but compromised mailboxes can still reply in genuine threads."], prerequisites=["stored Message-ID and thread-reference headers"]),
    _f("thread_continuation_changed_infrastructure", "Thread continuation uses changed sender infrastructure", "situational", "Thread and Relationship History", "Heavy",
       "Requires an exact In-Reply-To/References match to an earlier case Message-ID plus participant overlap, then checks whether Reply-To, Return-Path domain, or trusted sending IP is newly observed for that counterpart. Subject equality is not required for this factor.",
       suspicious=["A genuine vendor thread continues with a changed subject such as 'Invoice — URGENT updated bank details', while replies now route to a new domain or the message arrives from a never-before-seen boundary IP."],
       legitimate=["A vendor may migrate mail providers, change routing, or add a new support mailbox."], prerequisites=["stored thread references", "case history"]),
    _f("prior_sender_recipient", "Prior sender-recipient relationship", "situational", "Thread and Relationship History", "Heavy",
       "Searches earlier messages for the same sender and at least one matching recipient address.",
       suspicious=["Can be positive for a campaign targeting established relationships."],
       legitimate=["Can be negative when prior correspondence is reassuring."], prerequisites=["recipient data"]),
    _f("prior_sender_subject", "Prior sender and normalized subject pair", "situational", "Thread and Relationship History", "Heavy",
       "Searches earlier messages for the same sender and subject after removing common reply/forward prefixes and normalizing whitespace.",
       suspicious=["A known campaign repeatedly reuses a sender-subject signature."],
       legitimate=["Recurring legitimate notifications commonly reuse subjects."]),
    _f("reply_subject_without_references", "Subject appears to be a reply, but no thread-reference headers are present", "situational", "Thread and Relationship History", "Moderate",
       "Checks for a reply-style subject prefix while In-Reply-To and References are absent.",
       suspicious=["Re: Updated payment instructions with no thread headers."],
       legitimate=["Exports and some mail clients may omit threading headers."], prerequisites=["stored raw headers"]),
    _f("unmatched_thread_references", "Thread-reference headers do not match any earlier message in the case", "situational", "Thread and Relationship History", "Heavy",
       "Checks whether present In-Reply-To/References values fail to match any earlier case Message-ID.",
       suspicious=["Fabricated thread references may not match collected history."],
       legitimate=["The referenced message may simply be outside the collected mailbox data."], prerequisites=["stored Message-ID and thread-reference headers"]),

    # Situational — authentication/routing
    _f("trusted_arc_fail", "Trusted ARC check failed", "situational", "Authentication and Routing Context", "Light",
       "Uses only a stored ARC result marked trusted by conservative PST-corpus inference and explicitly reporting failure.",
       suspicious=["arc=fail from a PST-inferred trusted authentication service"],
       legitimate=["Forwarding and intermediary modification can produce legitimate ARC problems."], prerequisites=["trusted authentication-result classification"]),
    _f("authentication_conflict", "Authentication results conflict across headers", "situational", "Authentication and Routing Context", "Moderate",
       "Compares multiple stored Authentication-Results records for pass/fail contradictions and records trusted status.",
       suspicious=["Untrusted header says DMARC pass while trusted gateway says fail."],
       legitimate=["Multiple legitimate gateways can observe different results after forwarding or modification."], prerequisites=["multiple authentication-result records"]),
    _f("date_received_discrepancy", "Message date differs substantially from trusted Received time", "situational", "Authentication and Routing Context", "Light",
       "Uses the existing stored date discrepancy and a user-configured absolute threshold.",
       suspicious=["Header Date differs from trusted Received time by 53 hours."],
       legitimate=["Queue delays, migrations, and bad clocks can also create discrepancies."],
       parameters=[_p("threshold_hours", "Difference threshold (hours)", "integer", default=24, minimum=0)], prerequisites=["trusted Received timestamp"]),
    _f("message_id_missing_or_malformed", "Message-ID is missing or malformed", "situational", "Authentication and Routing Context", "Light",
       "Uses the stored Message-ID and conservative local syntax validation. No domain lookup is performed.",
       suspicious=["No Message-ID or Message-ID: invoice-12345"],
       legitimate=["Drafts, locally created MSG files, and unusual systems may omit it."]),
    _f("message_id_domain_mismatch", "Message-ID domain differs from visible From domain", "situational", "Authentication and Routing Context", "Light",
       "Compares registrable domains in the stored Message-ID and From address.",
       suspicious=["From billing@company.com; Message-ID <id@unrelated.test>"],
       legitimate=["Marketing, ticketing, and delegated platforms often generate their own Message-ID domain."]),

    # Situational — URL characteristics
    _f("sharepoint_host_mismatch", "SharePoint link differs from configured legitimate SharePoint host", "situational", "URL Characteristics", "Moderate",
       "Runs only when the analyst supplies a legitimate SharePoint hostname. Any stored URL containing SharePoint keywords but not matching that host can trigger.",
       suspicious=["Configured company.sharepoint.com; message links to unfamiliar.sharepoint.com"],
       legitimate=["External collaboration commonly uses another organization's SharePoint tenant."],
       parameters=[_p("legitimate_sharepoint_host", "Legitimate SharePoint host", "text", placeholder="companyname.sharepoint.com")], prerequisites=["URL indexing"]),
    _f("external_sharepoint_tenant_new", "External SharePoint tenant is newly observed in the case", "situational", "URL Characteristics", "Heavy",
       "Requires a configured legitimate host, identifies a mismatched SharePoint tenant, and checks whether it appeared in earlier case messages.",
       suspicious=["A newly introduced external tenant appears during a credential-phishing campaign."],
       legitimate=["A new collaboration partner also introduces a new tenant."],
       parameters=[_p("legitimate_sharepoint_host", "Legitimate SharePoint host", "text", placeholder="companyname.sharepoint.com")], prerequisites=["URL indexing"]),
    _f("payment_urgency_keywords", "Payment-change or urgency language is present", "situational", "Campaign Signatures", "Moderate",
       "Searches the stored subject and body text for a configurable case-insensitive phrase list and optional IBAN, routing-number, and account-number patterns.",
       suspicious=["updated bank details", "urgent wire", "gift cards", "IBAN DE89..."],
       legitimate=["Finance teams and vendors routinely discuss payments, banking, and deadlines."],
       parameters=[
           _p("keywords", "Keywords or phrases", "multiline", default="updated bank details\nchange bank details\nwire\nurgent\ngift card\niban\nrouting number\naccount number"),
           _p("include_financial_patterns", "Include IBAN/routing/account-number patterns", "boolean", default=True),
       ], prerequisites=["stored subject/body text"]),
    _f("exact_url_count", "Exact number of URLs in message", "situational", "Campaign Signatures", "Moderate",
       "Matches the exact complete URL count recorded by Threadsaw. No URL types or duplicates are omitted from the stored count.",
       suspicious=["Known campaign samples consistently contain exactly 2 URLs."],
       legitimate=["This is a campaign signature, not a universal risk signal."],
       parameters=[_p("expected_count", "Expected URL count", "integer", default=0, minimum=0)], prerequisites=["URL indexing"]),
    _f("url_shortener", "URL uses a known shortening service", "situational", "URL Characteristics", "Moderate",
       "Compares stored URL hosts with a bundled, versioned local list of common shortening services. No redirect is followed.",
       suspicious=["bit.ly or tinyurl.com link conceals the destination."],
       legitimate=["Shorteners are common in legitimate notifications and social media."], prerequisites=["URL indexing", "bundled shortener list"]),
    _f("url_punycode", "URL hostname contains Punycode", "situational", "URL Characteristics", "Moderate",
       "Checks stored URL hostnames for xn-- labels and decodes locally for analyst review.",
       suspicious=["A lookalike hostname encoded with Punycode."], legitimate=["Internationalized domains legitimately use Punycode."], prerequisites=["URL indexing"]),
    _f("url_domain_new_case", "URL destination domain is newly observed in the case", "situational", "URL Characteristics", "Heavy",
       "Checks whether any destination registrable domain was absent from all earlier case messages.",
       suspicious=["New credential-harvesting infrastructure appears in the hunt window."],
       legitimate=["Legitimate correspondence regularly introduces new domains."], prerequisites=["URL indexing"]),
    _f("url_domain_new_sender", "URL destination domain is newly observed for that sender", "situational", "URL Characteristics", "Heavy",
       "Checks whether an established sender links to a destination domain never seen in that sender's earlier messages.",
       suspicious=["A known vendor suddenly links to an unfamiliar host."],
       legitimate=["Vendors adopt new platforms and services."], prerequisites=["URL indexing"]),
    _f("url_deep_subdomains", "URL hostname has unusually deep subdomain nesting", "situational", "URL Characteristics", "Moderate",
       "Counts labels before the registrable domain and compares with an analyst-supplied minimum depth.",
       suspicious=["secure.login.account.company.attacker.test"],
       legitimate=["Cloud and enterprise services can use deeply nested legitimate hostnames."],
       parameters=[_p("minimum_depth", "Minimum subdomain depth", "integer", default=4, minimum=1)], prerequisites=["URL indexing"]),
    _f("url_nested_url", "URL contains another full URL inside its query string or fragment", "situational", "URL Characteristics", "Moderate",
       "Locally decodes bounded query/fragment values and checks for an embedded complete HTTP(S) URL without following either URL.",
       suspicious=["https://redirector.test/?target=https%3A%2F%2Fattacker.test"],
       legitimate=["Marketing, authentication, and security rewriting commonly embed destination URLs."], prerequisites=["URL indexing"]),
    _f("url_plain_http", "URL uses plain HTTP rather than HTTPS", "situational", "URL Characteristics", "Moderate",
       "Checks stored web URLs for the http scheme and never connects to them.",
       suspicious=["http://example.test/login"], legitimate=["Legacy and internal systems may legitimately use HTTP."], prerequisites=["URL indexing"]),
    _f("url_heavy_percent_encoding", "URL contains unusually heavy percent-encoding", "situational", "URL Characteristics", "Moderate",
       "Counts %xx sequences in stored URL text and compares with an analyst-supplied threshold using a bounded local decoder.",
       suspicious=["A path or query with many encoded characters obscures its visible content."],
       legitimate=["Tracking and authentication links frequently use heavy encoding."],
       parameters=[_p("minimum_sequences", "Minimum percent-encoded sequences", "integer", default=8, minimum=1)], prerequisites=["URL indexing"]),
    _f("url_base64_like", "URL contains a large Base64-like encoded value", "situational", "URL Characteristics", "Moderate",
       "Checks URL path/query/fragment values for long Base64 or URL-safe Base64 patterns; decoding is local, bounded, and never executed.",
       suspicious=["A long encoded query value conceals recipient or destination data."],
       legitimate=["Authentication and tracking links often contain long tokens."],
       parameters=[_p("minimum_length", "Minimum encoded-value length", "integer", default=40, minimum=8)], prerequisites=["URL indexing"]),
    _f("url_contains_recipient_email", "URL contains a recipient email address", "situational", "URL Characteristics", "Moderate",
       "Checks literal and locally decoded URL text for a complete recorded recipient email address.",
       suspicious=["Credential link includes employee%40company.com as a parameter."],
       legitimate=["Unsubscribe and account-management links often contain recipient identifiers."], prerequisites=["URL indexing", "recipient data"]),
    _f("url_domain_differs_sender", "URL destination domain differs from sender domain", "situational", "URL Characteristics", "Moderate",
       "Compares every stored destination registrable domain with the sender domain. No URLs are omitted.",
       suspicious=["A purported vendor links to unrelated credential infrastructure."],
       legitimate=["Organizations routinely link to Microsoft, Google, payment processors, and other third parties."], prerequisites=["URL indexing"]),

    # Situational — attachment characteristics
    _f("exact_attachment_count", "Exact number of attachments in message", "situational", "Campaign Signatures", "Light",
       "Matches the exact complete attachment count stored by Threadsaw. No attachment types are omitted.",
       suspicious=["Known samples consistently contain exactly one attachment."],
       legitimate=["This is a campaign signature rather than an inherent risk indicator."],
       parameters=[_p("expected_count", "Expected attachment count", "integer", default=0, minimum=0)], prerequisites=["attachment metadata"]),
    _f("attachment_type_match", "Attachment type matches a configured value", "situational", "Attachment Characteristics", "Moderate",
       "Matches either a stored filename extension or stored detected type using a case-insensitive exact comparison.",
       suspicious=["Known campaign consistently delivers HTML attachments."],
       legitimate=["The same type may be routine in another environment."],
       parameters=[_p("match_field", "Match field", "choice", choices=["Filename extension", "Detected file type"], default="Filename extension"),
                   _p("match_value", "Value", "text")], prerequisites=["attachment metadata"]),
    _f("attachment_type_new_sender", "Attachment type is newly observed for that sender", "situational", "Attachment Characteristics", "Heavy",
       "Compares current attachment types with earlier messages from the same sender using existing metadata only.",
       suspicious=["A sender that historically sends PDF/XLSX suddenly sends HTML."],
       legitimate=["Legitimate senders begin using new file formats."], prerequisites=["attachment metadata"]),
    _f("attachment_archive", "Attachment is an archive", "situational", "Attachment Characteristics", "Light",
       "Checks stored attachment filename extensions and declared MIME types for common archive formats. It does not open, extract, or inspect archive contents during scoring.",
       suspicious=["A campaign consistently delivers ZIP, 7Z, RAR, TAR, GZ, BZ2, XZ, CAB, or similar archives."],
       legitimate=["Archives are commonly used for legitimate file transfer and software distribution."],
       prerequisites=["attachment metadata"],
       false_positive="This factor identifies archive packaging only; it does not determine whether the archive is encrypted, malicious, or safe."),
    _f("attachment_encrypted_zip", "Attachment is an encrypted or password-protected ZIP-family archive", "situational", "Attachment Characteristics", "Moderate",
       "Uses bounded ZIP central-directory metadata to identify archive members whose encryption flag is set. Threadsaw never extracts or decrypts the archive and does not attempt a password.",
       suspicious=["A ZIP attachment contains one or more encrypted members and the message supplies a password or asks the recipient to open it."],
       legitimate=["Organizations may legitimately use password-protected ZIP files to transfer sensitive material."],
       prerequisites=["stored ZIP-family attachment bytes", "bounded archive inventory"],
       false_positive="The ZIP encryption flag strongly suggests protected content but does not establish maliciousness or prove which password mechanism was used."),
    _f("attached_email", "Message contains an attached email message", "situational", "Attachment Characteristics", "Light",
       "Checks stored MIME type/extension metadata for EML, MSG, or message/rfc822 without recursively parsing it during scoring.",
       suspicious=["An attached message conceals or reproduces campaign content."],
       legitimate=["Forwarding and abuse reporting commonly attach original emails."], prerequisites=["attachment metadata"]),

    # Situational — recipient/direction
    _f("sender_recipient_same_domain", "Sender and recipient share the same domain", "situational", "Recipient and Message Direction", "Light",
       "Checks whether the sender registrable domain matches at least one To, CC, or preserved BCC recipient domain.",
       suspicious=["Can be weighted upward during an internal-account-compromise hunt."],
       legitimate=["Can be weighted downward during an external-phishing hunt, but internal spoofing/compromise remains possible."],
       prerequisites=["recipient data"], implemented=True, evaluator_version="1"),
    _f("sender_mimics_recipient_localpart", "Sender address mimics a recipient local part on another domain", "situational", "Recipient and Message Direction", "Moderate",
       "Checks whether sender and recipient share the same mailbox name before @ while their registrable domains differ.",
       suspicious=["From janesmith@external.test to janesmith@company.com"],
       legitimate=["Generic local parts such as info, billing, or support can legitimately recur across organizations."], prerequisites=["recipient data"]),
    _f("no_visible_recipient", "Message contains no visible recipient address", "situational", "Recipient and Message Direction", "Light",
       "Checks whether no usable To or CC address is present. It does not infer BCC use.",
       suspicious=["Bulk campaign hides all visible recipients."],
       legitimate=["Mailing lists and privacy-preserving notifications often omit visible recipients."], prerequisites=["recipient data"]),
    _f("bcc_only_recipients", "Message contains recipients only in BCC", "situational", "Recipient and Message Direction", "Light",
       "Requires affirmative preserved BCC recipients plus no usable To or CC recipients. Missing BCC data returns UNKNOWN.",
       suspicious=["Concealed-recipient campaign sent only through BCC."],
       legitimate=["Newsletters and privacy-sensitive communications can use BCC."], prerequisites=["preserved BCC data"]),
]


IMPLEMENTED_FACTOR_IDS = {
    "reply_to_domain_mismatch", "display_name_embedded_email_domain_mismatch",
    "sender_domain_lookalike_configured", "sender_domain_lookalike_recipient",
    "trusted_dmarc_fail", "trusted_dkim_fail", "trusted_spf_fail",
    "displayed_url_domain_mismatch", "url_literal_ip", "url_userinfo_misdirection",
    "url_nonstandard_port", "url_dangerous_scheme", "url_embeds_legitimate_domain",
    "url_obfuscated_numeric_ip", "attachment_executable_or_script",
    "attachment_double_extension", "attachment_unicode_controls",
    "executable_without_extension", "attachment_shortcut", "attachment_disk_image",
    "attachment_html_svg", "attachment_modern_loader_or_macro",
    "html_form", "html_auto_redirect", "html_embedded_active_object",
    "html_script", "html_event_handlers", "return_path_domain_mismatch",
    "sender_address_new", "sender_domain_new", "sender_ip_new_for_sender",
    "reply_to_new_for_sender", "return_path_new_for_sender",
    "sender_free_email_provider", "sender_domain_punycode", "sender_header_mismatch",
    "corroborated_thread_reply", "thread_continuation_changed_infrastructure", "prior_sender_recipient", "prior_sender_subject",
    "reply_subject_without_references", "unmatched_thread_references",
    "trusted_arc_fail", "authentication_conflict", "date_received_discrepancy",
    "message_id_missing_or_malformed", "message_id_domain_mismatch",
    "sharepoint_host_mismatch", "external_sharepoint_tenant_new", "payment_urgency_keywords", "exact_url_count",
    "url_shortener", "url_punycode", "url_domain_new_case", "url_domain_new_sender",
    "url_deep_subdomains", "url_nested_url", "url_plain_http",
    "url_heavy_percent_encoding", "url_base64_like", "url_contains_recipient_email",
    "url_domain_differs_sender", "exact_attachment_count", "attachment_type_match",
    "attachment_type_new_sender", "attachment_archive", "attachment_encrypted_zip", "attached_email", "sender_recipient_same_domain",
    "sender_mimics_recipient_localpart", "no_visible_recipient", "bcc_only_recipients",
}

for _item in FACTOR_CATALOG:
    _item["implemented"] = _item["factor_id"] in IMPLEMENTED_FACTOR_IDS
    if _item["implemented"]:
        _item["evaluator_version"] = "1"

# Backward-compatible hidden factor retained for old 0.3.x configuration files.
LEGACY_FACTORS: list[dict[str, Any]] = [
    _f(
        "exact_unique_url_domains",
        "Exact number of unique URL destination domains (removed)",
        "situational",
        "Legacy",
        "Moderate",
        "Removed from the visible Phish Hunt catalog in 0.6.0. Retained only so older saved configurations can be imported and explained as unavailable.",
        parameters=[_p("expected_count", "Expected unique-domain count", "integer", default=0, minimum=0)],
        implemented=False,
        evaluator_version="removed-0.6.0",
    ),
    _f(
        "html_script_or_event_handlers",
        "HTML body contains script code or JavaScript event handlers (legacy combined factor)",
        "inherently_risky",
        "Legacy",
        "Moderate",
        "Legacy combined factor retained for imported 1.0.0 configurations. New presets use separate script-element and event-handler factors.",
        implemented=True,
        evaluator_version="1",
    ),
    _f(
        "cross_domain_message",
        "Sender and recipient domains differ (legacy prototype)",
        "situational",
        "Legacy",
        "Light",
        "Legacy 0.3.x prototype factor. It remains accepted by the scoring engine but is not shown in the current GUI catalog.",
        implemented=True,
        evaluator_version="1",
    )
]

# Factors whose meaning depends on historical or cross-message context from the
# complete case database.  Evaluate Phishing Email uses this metadata to avoid
# implying that a standalone EML/MSG can answer case-history questions.
CASE_HISTORY_FACTOR_IDS = {
    "sender_address_new",
    "sender_domain_new",
    "sender_ip_new_for_sender",
    "reply_to_new_for_sender",
    "return_path_new_for_sender",
    "corroborated_thread_reply",
    "thread_continuation_changed_infrastructure",
    "prior_sender_recipient",
    "prior_sender_subject",
    "unmatched_thread_references",
    "external_sharepoint_tenant_new",
    "url_domain_new_case",
    "url_domain_new_sender",
    "attachment_type_new_sender",
}

for _item in [*FACTOR_CATALOG, *LEGACY_FACTORS]:
    _item["requires_case_history"] = _item["factor_id"] in CASE_HISTORY_FACTOR_IDS

FACTOR_BY_ID = {item["factor_id"]: item for item in [*FACTOR_CATALOG, *LEGACY_FACTORS]}


def factor_catalog_document() -> list[dict[str, Any]]:
    """Return safe copies suitable for GUI or JSON display."""
    return [dict(item) for item in FACTOR_CATALOG]
